
# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms_tweet
    username: postgres
    password: admin
  # JPA properties
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
# Server configuration
server:
  port: 8080